# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PwJwqOs8XoxHr4mUcvSgVumAxhTX0QZj
"""

from datetime import datetime
name=input("Enter your Name:")
age=int(input("Enter your Age"))
var=int((100-age)+datetime.now().year)
print('Hi %s. Your age is %s. You will turn 100 in the year %s' %(name,age,var))

num=int(input("Enter the number of times you want to print the message:"))
for x in range(num):
  print('Hi %s. Your age is %s. You will turn 100 in the year %s' %(name,age,var))

num=int(input("Enter the number of times you want to print the message:"))
for x in range(num):
  print('Hi %s. Your age is %s. You will turn 100 in the year %s \n' %(name,age,var))

a= [1,1,2,3,5,8,13,21,34,55,89]
b=[]
for x in a:
  if x<5:
    b.append(x)
print(b)

a= [1,1,2,3,5,8,13,21,34,55,89]
for x in a: 
  if x<5:
    print(x)

[print(x) for x in b]

number2=int(input("Enter the number:"))
for x in a:
  if x<number2:
    print(x)

def fibo(n):
  if n<=1:
    return n
  else:
      return(fibo(n-1)+fibo(n-2))

terms=int(input("Number of terms"))
if terms<=0:
  print("Enter a positive interger")
else:
  print("fibonacci Series")
  for i in range(terms):
    print(fibo(i))

list1 = [1,1,2,3,5,8,13,3,5,6,1]
list2=[]
for i in list1:
  if i not in list2:
    list2.append(i)

print("The original list is" + str(list1))
print("New list without duplicates is" + str(list2))

list1 = [1,1,2,3,5,8,13,3,5,6,1]
def func(list1):
  list3=[]
  for i in list1:
    if  i not in list3:
      list3.append(i)
  print("New list is" +str(list3))

func(list1)

def func2(list1):
  newlist=list(set(list1))
  print("New List" +str(newlist))

func2(list1)

num=int(input("Enter the number that you want to check"))

def Prime(num1):
  flag= False
  if num1>1:
    for i in range(2,num1):
      if(num1%i) ==0:
        flag =True
        break
  if flag:
    print("%s is not prime" %(num1))
  else:
    print("%s in prime" %(num1))

Prime(num)